spring:
  application:
    name: ${SPRING_APP_NAME:spring-sec-section6}
    username: KUNG FU PANDA-PROD
  data:
    mongodb:
      host: ${DB_SERVER_HOST:localhost}
      port: ${DB_SERVER_PORT:27017}
      database: ${DB_NAME:easybank}

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.security : ${SPRING_SECURITY_LOG_LEVEL:TRACE}
